{
 "title": "Local GPS & Sensor Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Systematic Longitude Drift (15m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Local Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT mean(\"lon\") FROM \"local_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    },
    {
     "alias": "OpenSky Average",
     "query": "SELECT mean(\"lon\") FROM \"global_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    }
   ]
  },
  {
   "title": "Systematic Latitude Drift (15m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Local Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT mean(\"lat\") FROM \"local_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    },
    {
     "alias": "OpenSky Average",
     "query": "SELECT mean(\"lat\") FROM \"global_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    }
   ]
  },
  {
   "title": "Systematic Altitude Drift (15m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "alias": "Local Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT mean(\"alt_baro_ft\") FROM \"local_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    },
    {
     "alias": "OpenSky Average",
     "query": "SELECT mean(\"baro_alt_m\") FROM \"global_aircraft_state\" WHERE $timeFilter GROUP BY time(1m) fill(linear)"
    }
   ]
  },
  {
   "title": "The Integrity Monitor",
   "type": "timeseries",
   "description": "Detects Fake Signals (HDOP/VDOP)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "SELECT mean(\"hdop\") AS \"Longitude_Error\", mean(\"vdop\") AS \"Latitude_Error\" FROM \"gps_data\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "GPS Fix Status",
   "type": "state-timeline",
   "description": "Jamming Detector",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "alias": "GPS Status",
     "query": "SELECT last(\"mode\") FROM \"gps_data\" WHERE (\"host\" = 'rpi4-adsb') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "RSSI (Signal Quality)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "Decibel",
     "query": "SELECT mean(\"avg_rssi\") FROM \"adsb_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "MAX RANGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "alias": "Kilometers",
     "query": "SELECT max(\"max_range_km\") FROM \"adsb_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_stats",
     "select": [
      [
       { "params": [ "cpu_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_stats",
     "query": "SELECT max(\"disk_usage\") FROM \"system_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_stats",
     "select": [
      [
       { "params": [ "ram_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_stats",
     "query": "SELECT max(\"disk_usage\") FROM \"system_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "disk_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}